# Generated by Django 5.0.6 on 2024-06-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('quantityAvl', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
