# Generated by Django 5.0.6 on 2024-07-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShopName', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone', models.CharField(blank=True, max_length=20)),
                ('CompanyAddress', models.CharField(blank=True, max_length=255)),
                ('TaxIdentificationNumber', models.CharField(blank=True, max_length=50)),
                ('PickupAddress', models.CharField(blank=True, max_length=255)),
                ('BankAccountName', models.CharField(blank=True, max_length=255)),
                ('BankName', models.CharField(blank=True, max_length=255)),
                ('AccountNumber', models.CharField(blank=True, max_length=50)),
                ('Description', models.TextField(blank=True)),
                ('Website', models.URLField(blank=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='competition',
            options={},
        ),
    ]
