# Generated by Django 5.0.6 on 2024-07-22 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField(blank=True, null=True)),
                ('query', models.TextField(verbose_name='Query')),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('flag', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_items', to='products.order')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
