# Generated by Django 5.0.6 on 2024-07-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_customer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='sellerpoints',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
