# Generated by Django 5.0.6 on 2024-07-22 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_extraitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='extraitem',
            name='product_id',
        ),
        migrations.AddField(
            model_name='extraitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='products.product'),
            preserve_default=False,
        ),
    ]
