# Generated by Django 5.0.6 on 2024-07-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_seller_alter_competition_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=255)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('Phone', models.CharField(blank=True, max_length=20)),
                ('AddressLine1', models.CharField(max_length=255)),
                ('AddressLine2', models.CharField(blank=True, max_length=255)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('PostalCode', models.CharField(max_length=20)),
                ('Country', models.CharField(max_length=100)),
                ('ShippingInstructions', models.TextField(blank=True)),
                ('ShippingMethod', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={},
        ),
    ]
