# Generated by Django 5.0.6 on 2024-07-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_customer_is_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='Phone',
        ),
        migrations.AlterField(
            model_name='seller',
            name='AccountNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='BankAccountName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='BankName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='CompanyAddress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='PickupAddress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='Products',
            field=models.ManyToManyField(blank=True, null=True, related_name='Sellers', to='products.product'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='ShopName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='TaxIdentificationNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='Website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
