# Generated by Django 5.0.6 on 2024-07-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.CharField(max_length=10),
        ),
    ]
