# Generated by Django 5.0.6 on 2024-07-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_orderitem_order_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="extraitem",
            name="read",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Notifications",
        ),
    ]
