# Generated by Django 5.0.6 on 2024-06-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_quantityavl'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productPhoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
