# Generated by Django 5.0.6 on 2024-07-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_extraitem_read_delete_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='units',
            field=models.CharField(default='Kg', max_length=20),
        ),
    ]
