# Generated by Django 5.0.6 on 2024-07-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_extraitem_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_food',
            field=models.BooleanField(default=False),
        ),
    ]
