# Generated by Django 5.0.6 on 2024-07-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_customer_options_alter_customer_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.CharField(default='NewLocation', max_length=50),
            preserve_default=False,
        ),
    ]
